### ISSUE TITLE
segmentation fault (core dumped)

### ISSUE THREAD

**Issue by JianqiangDing** [kal39/TerminalMediaViewer#15]
Hi, there may be a bug occurred when I test the project locally, I was testing the project with Linux Mint 19.3 (cinnamon desktop), and the terminal reports segmentation fault.
I installed FFmpeg  3.4.6 using apt-get, all the other requirements have been installed in the same way, am I missing something? The building succeeded, but crashed with a segmentation fault, why?? any advice?
I was using the sample video downloaded from [TEST VIDEOS](https://test-videos.co.uk/bigbuckbunny/mp4-h264)

**Comment by kai-kj** [comment]
Can you build with `make debug` and run tmv after that.   
It should show some debug messages.   
Can you tell me where you got the segmentation fault?

**Comment by JianqiangDing** [comment]
Hi, here are the messages
![image](https://user-images.githubusercontent.com/7833870/82013551-273c6700-96ad-11ea-9070-7172392bca62.png)

**Comment by kai-kj** [comment]
Just to check, your pull request didn't fix this problem didn't it?

**Comment by JianqiangDing** [comment]
no, I just refine the README which missed mentioning a required third party library, did you reproduce the bug??

**Comment by kai-kj** [comment]
It should be fixed now.  
Mint uses an older version of ffmpeg (3.4.6) so there was a function (`av_register_all()`) it needed to call before loading videos.  
Can you check if it works?

**Comment by JianqiangDing** [comment]
thanks, the bug fixed now. everything works fine now.
