### ISSUE TITLE
compilation on osx

### ISSUE THREAD

**Issue by evandrix** [kal39/TerminalMediaViewer#2]
1. `brew install argp-standalone ffmpeg`

2. 
```
LIBS = -I/usr/local/include -I/usr/local/opt/ffmpeg/include -L/usr/local/lib -L/usr/local/opt/ffmpeg/lib
FLAGS = -largp -lm -lavcodec -lavformat -lavfilter -lavdevice -lswresample -lswscale -lavutil -lpthread -ldl
```

**Comment by kai-kj** [comment]
There should me compilation instructions for osx now

**Comment by drselump14** [comment]
`make -f makefile.macos` gives me `No such file or directory` , did I miss something here?

**Comment by kai-kj** [comment]
I'm going to look into it but I don't have a mac right now so it might take a day or so, sorry.

**Comment by kai-kj** [comment]
Sorry if I'm late.
I've updated the the build process and README so should be working now.
Clone the repo and run `make` or `(sudo) make install`.

**Comment by drselump14** [comment]
wow, nice ! ... it works .. thanks a lot

**Comment by kai-kj** [comment]
no problem
